import { Inter } from 'next/font/google';
import './css/bootstrap-5/css/bootstrap.min.css';
import './css/acss/acss.css'
import './css/fontawesome/css/all.min.css'
import './globals.css'
import './css/animate.min.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container">
       <h1 class="sz-20 mt-2"> Qui<span class="text-danger animate__animated animate__bounce animate__infinie animate__delay-3s" style={{display:'inline-block'}}>zz</span>ify </h1>
      {children}</body>
    </html>
  )
}
