# Generated by Django 4.2.2 on 2024-04-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_game_gametype'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
