# Generated by Django 4.2.2 on 2024-01-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_game_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='code',
            field=models.CharField(blank=True, max_length=2000000, null=True),
        ),
    ]
