# Generated by Django 4.2.2 on 2024-01-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_game_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=2000000, null=True, unique=True),
        ),
    ]
