# Generated by Django 4.2.2 on 2024-05-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_rename_status_game_active_remove_game_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='multiplayer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.IntegerField(default=20),
        ),
    ]
