# Generated by Django 4.2.2 on 2024-11-02 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_game_multiplayer_alter_game_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000000)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_host', to='question.profile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='game', to='question.profile'),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_points', to='question.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='question.profile')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='question.gamemode'),
        ),
    ]
