# Generated by Django 4.2.2 on 2024-11-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_alter_question_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='game', to='question.profile'),
        ),
        migrations.AlterField(
            model_name='gamemode',
            name='name',
            field=models.CharField(max_length=2000000, unique=True),
        ),
    ]
