# Generated by Django 4.2.2 on 2024-11-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0012_alter_game_players_alter_gamemode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemode',
            name='intstructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
