# Generated by Django 5.1.4 on 2025-01-18 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0015_alter_option_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamemode",
            old_name="intstructions",
            new_name="instructions",
        ),
        migrations.AddField(
            model_name="gamemode",
            name="locked",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="gamemode",
            name="player",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gameMode",
                to="question.player",
            ),
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirm", models.BooleanField(default=False)),
                ("sound", models.BooleanField(default=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="question.profile",
                    ),
                ),
            ],
        ),
    ]
