# Generated by Django 5.1.4 on 2025-01-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0016_rename_intstructions_gamemode_instructions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamemode",
            name="icon",
            field=models.CharField(default="fas fa-", max_length=200),
        ),
        migrations.AddField(
            model_name="gamemode",
            name="score",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="gamemode",
            name="time",
            field=models.IntegerField(default=20),
        ),
    ]
