# Generated by Django 5.1.4 on 2025-01-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0017_gamemode_icon_gamemode_score_gamemode_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamemode",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
