# Generated by Django 5.1.4 on 2025-01-18 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0019_alter_gamemode_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamemode",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gameMode",
                to="question.profile",
            ),
        ),
    ]
