# Generated by Django 5.1.4 on 2025-01-18 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0020_alter_gamemode_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamemode",
            name="locked",
        ),
        migrations.RemoveField(
            model_name="gamemode",
            name="player",
        ),
        migrations.CreateModel(
            name="ProfileGameMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locked", models.BooleanField(default=True)),
                (
                    "mode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question.gamemode",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gameMode",
                        to="question.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "mode")},
            },
        ),
        migrations.DeleteModel(
            name="Player",
        ),
    ]
