# Generated by Django 5.1.4 on 2025-01-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0022_player_alter_profilegamemode_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamemode",
            name="profiles",
            field=models.ManyToManyField(
                related_name="gameMode", to="question.profile"
            ),
        ),
        migrations.DeleteModel(
            name="ProfileGameMode",
        ),
    ]
