# Generated by Django 5.1.4 on 2025-01-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0023_gamemode_profiles_delete_profilegamemode"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamemode",
            name="verified_profile",
            field=models.BooleanField(default=True),
        ),
    ]
