# Generated by Django 5.1.4 on 2026-05-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0024_gamemode_verified_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamemode",
            name="profiles",
            field=models.ManyToManyField(
                blank=True, related_name="gameMode", to="question.profile"
            ),
        ),
    ]
