# Generated by Django 5.1.4 on 2026-05-12 22:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0025_alter_gamemode_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="fas fa-medal", max_length=50)),
                ("color", models.CharField(default="#f59e0b", max_length=7)),
                (
                    "requirement_type",
                    models.CharField(
                        choices=[
                            ("games_played", "Games Played"),
                            ("total_score", "Total Score"),
                            ("streak", "Streak"),
                            ("perfect_score", "Perfect Score"),
                        ],
                        max_length=50,
                    ),
                ),
                ("requirement_value", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GameAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("total_possible", models.IntegerField(default=0)),
                ("percentage", models.FloatField(default=0.0)),
                ("questions_answered", models.IntegerField(default=0)),
                ("correct_answers", models.IntegerField(default=0)),
                ("wrong_answers", models.IntegerField(default=0)),
                ("skipped_answers", models.IntegerField(default=0)),
                (
                    "time_taken_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("completed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="question.badge",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Player",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["order", "name"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="gamemode",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="level",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="option",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="points",
            options={"ordering": ["-score"], "verbose_name_plural": "Points"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"ordering": ["-total_points"]},
        ),
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["order", "id"]},
        ),
        migrations.RenameField(
            model_name="game",
            old_name="date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="game",
            name="gameType",
        ),
        migrations.RemoveField(
            model_name="game",
            name="players",
        ),
        migrations.RemoveField(
            model_name="game",
            name="question",
        ),
        migrations.RemoveField(
            model_name="game",
            name="time",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="points",
        ),
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default="#6366f1", max_length=7),
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(default="fas fa-tag", max_length=50),
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="game",
            name="avg_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="game",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="game",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="play_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="questions",
            field=models.ManyToManyField(
                blank=True, related_name="games", to="question.question"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="game",
            name="time_per_question",
            field=models.IntegerField(default=20, help_text="Seconds per question"),
        ),
        migrations.AddField(
            model_name="game",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="gamemode",
            name="color",
            field=models.CharField(
                default="#b8ff57", help_text="Hex color code", max_length=7
            ),
        ),
        migrations.AddField(
            model_name="gamemode",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="gamemode",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name="level",
            name="color",
            field=models.CharField(default="#f59e0b", max_length=7),
        ),
        migrations.AddField(
            model_name="level",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="level",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="option",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="points",
            name="attempts_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="points",
            name="best_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="points",
            name="last_played",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="current_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="joined_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_active",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_played_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="longest_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_games_played",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(
                blank=True, help_text="Explanation shown after answering (for learning)"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="hint",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="questions/"),
        ),
        migrations.AddField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="setting",
            name="daily_reminder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="setting",
            name="dark_mode",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="setting",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="game",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="question.category",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_games",
                to="question.profile",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="host",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosted_games",
                to="question.profile",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="mode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="question.gamemode",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="title",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gamemode",
            name="icon",
            field=models.CharField(default="fas fa-gamepad", max_length=50),
        ),
        migrations.AlterField(
            model_name="gamemode",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="gamemode",
            name="profiles",
            field=models.ManyToManyField(
                blank=True, related_name="unlocked_modes", to="question.profile"
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="answer",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="option",
            name="body",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="question.question",
            ),
        ),
        migrations.AlterField(
            model_name="points",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_records",
                to="question.game",
            ),
        ),
        migrations.AlterField(
            model_name="points",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_records",
                to="question.profile",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="about",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="question.level",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="confirm",
            field=models.BooleanField(
                default=False, help_text="Require confirmation before answering"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="points",
            unique_together={("game", "player")},
        ),
        migrations.AddField(
            model_name="gameattempt",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="question.game",
            ),
        ),
        migrations.AddField(
            model_name="gameattempt",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="question.profile",
            ),
        ),
        migrations.AddField(
            model_name="playerbadge",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="badges",
                to="question.profile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gameattempt",
            unique_together={("player", "game", "created_at")},
        ),
        migrations.AlterUniqueTogether(
            name="playerbadge",
            unique_together={("profile", "badge")},
        ),
    ]
