# Generated by Django 5.1.4 on 2026-05-13 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0026_badge_gameattempt_playerbadge_delete_player_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamemode",
            name="is_guest_allowed",
            field=models.BooleanField(
                default=False, help_text="Can guests play this mode without logging in?"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2026, 5, 13, 0, 10, 7, 225770),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="joined_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2026, 5, 13, 0, 10, 19, 979061),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2026, 5, 13, 0, 10, 29, 721635),
            ),
            preserve_default=False,
        ),
    ]
