# Generated by Django 5.1.4 on 2026-05-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0027_gamemode_is_guest_allowed_alter_game_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="mark",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
